export default{
    HeroHeading:'Make a Logo using AI',
    HeroSubHeading:'Logos for Everyone – Harnessing AI to Build Brands and Boost Identity.',
    HeroDesc:'Create a logo in seconds with our AI-powered logo maker. No design skills required. Try it now!',
    InputPlaceholder:'Enter your Logo Name',
    LogoTitle:'Logo Title',
    LogoTitleDesc:'Add Your Business, App, or Website Name for a Custom Logo',
    LogoDescTitle:'Describe Your Logo Vision',
    LogoDescDesc:'Tell us your ideas and inspirations—we’ll turn them into a logo that captures your brand perfectly.',
    LogoDescPlaceholder:'Enter your Logo description',
    LogoIdeaTitle:'Select Your Design Idea',
    LogoIdeaDesc:'Choose a design style that aligns with your vision, or skip to receive a random suggestion.',
    LogoDesignTitle:'Choose Your Logo Style',
    LogoDesignDesc:'Select the type of logo design that best represents your brands unique identity.',
    LogoColorPaletteTitle:'Choose Your Color Palette',
    LogoColorPaletteDesc:'Pick the colors that reflect your brands personality and create a lasting impression.',
    LogoPricingModelTitle:'Select your AI Model Plan',
    LogoPricingModelDesc:'Generate Unlimted Fast Logo with your fav model',
    LoadingWaitDesc:'✨ Please wait a moment while we work our magic to bring your logo to life.',
    LoadingWaitTitle:'Your logo is being created',
}